### ISSUE TITLE
setting pressure and running NPT simulation does not work

### ISSUE THREAD

**Issue by jkrajniak** [cgchemlab/chemlab#8]
The error is related 
```
Configure H5MD trajectory writer
Traceback (most recent call last):
  File "/user/leuven/307/vsc30783/vsc_data/software/chemlab/src/start_simulation.py", line 1075, in <module>
    main()
  File "/user/leuven/307/vsc30783/vsc_data/software/chemlab/src/start_simulation.py", line 582, in main
    chunk_size=256)  # int(NPart/MPI.COMM_WORLD.size))
  File "/user/leuven/307/vsc30783/vsc_data/software/2015a/espressopp/chem/espressopp/pmi.py", line 715, in __call__
    method_self.pmiobject = create(pmiobjectclass, *args, **kwds)
  File "/user/leuven/307/vsc30783/vsc_data/software/2015a/espressopp/chem/espressopp/pmi.py", line 320, in create
    obj = __workerCreate(cls, oid, *cargs, **ckwds)
  File "/user/leuven/307/vsc30783/vsc_data/software/2015a/espressopp/chem/espressopp/pmi.py", line 338, in __workerCreate
    obj = cls(*args, **kwds)
  File "/user/leuven/307/vsc30783/vsc_data/software/2015a/espressopp/chem/espressopp/io/DumpH5MD.py", line 209, in __init__
    self.box = part.box(
AttributeError: 'ParticlesGroup' object has no attribute 'box'
Exception RuntimeError: RuntimeError("Can't decrement id ref count (Can't close file, there are objects still open)",) in 'h5py._objects.ObjectID.__dealloc__' ignored
```

**Comment by jkrajniak** [comment]
Fixed with https://github.com/cgchemlab/chemlab/commit/880f7b92e29e81c8cc992dd00993d9b6bfeb7c82 and https://github.com/cgchemlab/espressopp/commit/05b8d71e24b40c51537fe00e6d7d522a32b063cb
